### ISSUE TITLE
[Blacklisted] 20200428.1413 - 20200501.0210 HKW

### ISSUE THREAD

**Issue by paul-breen** [SuperDARN/DDWG#3]
# Proposed File(s)

20200428.1413.00.hkw.rawacf.bz2
20200428.1625.00.hkw.rawacf.bz2
20200428.1804.00.hkw.rawacf.bz2
20200428.2016.00.hkw.rawacf.bz2
20200428.2228.00.hkw.rawacf.bz2
20200429.0007.00.hkw.rawacf.bz2
20200429.0219.00.hkw.rawacf.bz2
20200429.0431.00.hkw.rawacf.bz2
20200429.0610.00.hkw.rawacf.bz2
20200429.0822.00.hkw.rawacf.bz2
20200429.1034.00.hkw.rawacf.bz2
20200429.1213.00.hkw.rawacf.bz2
20200429.1425.00.hkw.rawacf.bz2
20200429.1604.00.hkw.rawacf.bz2
20200429.1816.00.hkw.rawacf.bz2
20200429.2028.00.hkw.rawacf.bz2
20200429.2207.00.hkw.rawacf.bz2
20200501.0031.00.hkw.rawacf.bz2
20200501.0210.00.hkw.rawacf.bz2

## Affiliated Mirror

Certainly on the BAS mirror, but probably also on VT/USask

## Reason

The files were highlighted by Nozomu Nishitani via email:

> 3. Removal of files  
> The hkw timing computer was down from 1413 UT on 28 Apr to 0511 UT on 1 May.  
> So please remove the files:  
> 20200428.1413.00.hkw.rawacf.bz2  
> to  
> 20200501.0210.00.hkw.rawacf.bz2   

### Potential Fix

I suspect not.

### Potential Removal

These are very small files (~3 kB compressed), so there's not much data in them.

**Comment by kevinkrieger** [comment]
Files blacklisted at USASK on June 8th ~23:00 UTC.

**Comment by paul-breen** [comment]
Files blacklisted at BAS on June 9th 15:36 UTC.

**Comment by kevinkrieger** [comment]
Hey Paul, thanks for doing that. I've added a label 'blacklisted_BAS', are you able to add labels
 or do you need more privileges in this repo?

**Comment by paul-breen** [comment]
Hi Kevin, I tried adding the label but didn't have sufficient privileges.

**Comment by kevinkrieger** [comment]
OK, I think I've now added you as a maintainer

**Comment by ksterne** [comment]
@paul-breen, @kevinkrieger, maybe they didn't make it to you, but I'm also seeing these files:

20200430.0019.00.hkw.rawacf.bz2  20200430.1225.00.hkw.rawacf.bz2
20200430.0231.00.hkw.rawacf.bz2  20200430.1404.00.hkw.rawacf.bz2
20200430.0410.00.hkw.rawacf.bz2  20200430.1616.00.hkw.rawacf.bz2
20200430.0622.00.hkw.rawacf.bz2  20200430.1828.00.hkw.rawacf.bz2
20200430.0834.00.hkw.rawacf.bz2  20200430.2007.00.hkw.rawacf.bz2
20200430.1013.00.hkw.rawacf.bz2  20200430.2219.00.hkw.rawacf.bz2

Those should be added to the list since they are within the date range.

**Comment by kevinkrieger** [comment]
Hi Kevin S., they didn't make it to the Globus mirror but I've now added them to the blocklist at USASK. Thanks for finding those.

**Comment by ksterne** [comment]
These files were accidentally downloaded to Virginia Tech again on Nov. 15th, 2020.  Just now I have removed them.  No higher data products than the fit-level data were impacted. I think we can re-close this issue.

**Comment by kevinkrieger** [comment]
I was wrong when commenting above on July 28th, I looked through my log files today and found that the files were indeed on the mirror and were placed there on May 2nd 2020. I removed them now thanks Paul for finding those. I'll close this issue now.
