### ISSUE TITLE
[Update] Relocation of dat to RAWACF files 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#39]
# Files 
2006 and earlier should be moved to a different folder if they were correct via dat file to mitigate confusion around how the files were created. 

## Mirrors To be Updated
- [X] Usask
- [X] BAS
- [X] VT

## Description
These files are created to help the process to higher-level product and DDWG distributes RAWACF files. However, since these files are created offsite and via dat files using a specific RST version more information needs to be provided on the metadata and process of processing these files. Thus create another folder where users have access to these files but aware that are not processed onsite.

**Comment by kevinkrieger** [comment]
there are some RAWACF files from 2006 that were legitimately produced at a radar site, so they will have to be differentiated from those that were processed using dat-to-rawacf

**Comment by mts299** [comment]
Didn't we complete this?

**Comment by kevinkrieger** [comment]
Correct! Closing now.
This was completed by October 6 2020
