### ISSUE TITLE
[Update] 20180620-20180708 LYR files

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#5]
# Files 
20180620.2201.00.lyr.rawacf.bz2
20180621.2201.00.lyr.rawacf.bz2
20180622.2201.00.lyr.rawacf.bz2
20180623.2201.00.lyr.rawacf.bz2
20180624.2201.00.lyr.rawacf.bz2
20180625.2201.00.lyr.rawacf.bz2
20180626.2201.00.lyr.rawacf.bz2
20180627.2201.00.lyr.rawacf.bz2
20180628.2201.00.lyr.rawacf.bz2
20180629.2201.00.lyr.rawacf.bz2
20180630.2201.00.lyr.rawacf.bz2
20180701.2201.00.lyr.rawacf.bz2
20180702.2201.00.lyr.rawacf.bz2
20180703.2201.00.lyr.rawacf.bz2
20180704.2201.00.lyr.rawacf.bz2
20180705.2201.00.lyr.rawacf.bz2
20180706.2201.00.lyr.rawacf.bz2
20180707.2201.00.lyr.rawacf.bz2
20180708.2201.00.lyr.rawacf.bz2

## Mirrors To be Updated
- [X] Usask
- [x] BAS

## Description
See above that there was a file transfer issue with the Longyearbyen data that has been corrected. The list of the corrected files can be found below. Please remove these files from your local repositories and download the corrected versions from the BAS mirror.

## Tasks 
- [ ] Remove versions of this file that were downloaded prior to or on 20180710
- [ ] Download new versions from BAS mirror

**Comment by kevinkrieger** [comment]
Usask never had the old files, so updating was not necessary.
BAS updated on July 10, 2018
